backend:
  name: github
  repo: LaChope/martinka-matu-blog
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Cover Image', name: 'image', widget: 'image', required: false }
      - { label: 'Image Description', name: 'hero_image_alt', widget: 'string' }
      - { label: 'Video Cover URL', name: 'video', widget: 'string', required: false }
      - { label: 'Video Title', name: 'video_title', widget: 'string' }
      - { label: 'Cover Title', name: 'hero_title', widget: 'string', required: false }
